Feat/Building domain layer
motoon-eg/dokan-store pull request #35
Opened 2022-07-02 11:57 UTC by HebaMad

2022-07-03 09:08 UTC, ahmdmhasn requested changes
Just few steps 💪

2022-07-03 09:08 UTC, ahmdmhasn commented on Dokan/Dokan/Assets.xcassets/AppIcon.appiconset/Contents.json
> +    },
To be removed

2022-07-03 09:08 UTC, ahmdmhasn commented on Domain/.gitignore
> +.DS_Store
File should be removed since we already have a .gitignore in the root directory

2022-07-03 09:08 UTC, ahmdmhasn commented on Domain/Sources/Domain/Model/User.swift
> +}
```suggestion
import Foundation

struct User {
    let id: Int
    let email: String
    let username: String
}
```

2022-07-03 09:08 UTC, ahmdmhasn commented on Domain/Sources/Domain/Model/UserRepository.swift
> +
```suggestion
protocol UserRepository {
    func fetchUserData() -> [User]
```

2022-07-03 09:08 UTC, ahmdmhasn commented on Networking/Sources/Networking/Model/BaseResponse.swift
> +//
Out of scope.. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on Networking/Sources/Networking/Model/ResponseData.swift
> +//
Out of scope.. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on Networking/Sources/Networking/Profile/ProfileNetworkable.swift
> +//
Out of scope.. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on Networking/Sources/Networking/Profile/ProfileTarget.swift
> +//
Out of scope.. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on Networking/Sources/Networking/Protocols/Networkable.swift
> +//
Out of scope.. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on Dokan/Dokan/Domain/Sources/Domain/Domain.swift
> +
Duplicated file. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on Dokan/Dokan/Domain/Tests/DomainTests/DomainTests.swift
> +import XCTest
Duplicated file. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on Dokan/Dokan/Domain/README.md
> +# Domain
Duplicated file. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on Dokan/Dokan/Domain/Package.swift
> +// swift-tools-version: 5.6
Duplicated file. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on Dokan/Dokan/Domain/.gitignore
> +.DS_Store
Duplicated file. Should be removed.

2022-07-03 09:08 UTC, ahmdmhasn commented on .gitignore
> +.DS_Store
```suggestion

# System files

.DS_Store
```

2022-07-04 21:07 UTC, ahmdyasser approved these changes

2022-07-05 18:46 UTC, ahmdmhasn commented on Dokan/Dokan/Domain/.gitignore
> +.DS_Store
Updated

2022-07-05 18:46 UTC, ahmdmhasn commented on Dokan/Dokan/Domain/Tests/DomainTests/DomainTests.swift
> +import XCTest
Not resolved

2022-07-06 11:47 UTC, ahmdmhasn approved these changes

2022-07-06 11:50 UTC, merged