add colors and fonts as extentions
motoon-eg/dokan-store pull request #53
Opened 2022-07-14 19:42 UTC by ziadali22

2022-07-14 20:01 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/Custom colors fonts/Font+Ext.swift
> +extension UIFont{
Let's separate buttons, labels and text fields each in a separate extension.

2022-07-14 20:05 UTC, ahmdmhasn requested changes
One more step closer.

2022-07-14 20:05 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/Custom colors fonts/Colors+Ext.swift
> +//  File.swift
- File should located in UIDokan/Extensions
- Change name to UIColors+Style

2022-07-14 20:05 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/Custom colors fonts/Font+Ext.swift
> +//  File.swift
- File should located in UIDokan/Extensions
- Change name to UIFont+ DMSans

2022-07-14 20:05 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/Custom colors fonts/Font+Ext.swift
> +extension UIFont{
Font's shouldn't have a dependency on the product, cover or any product related item. Let's find a generic names. 

Please refer to https://developer.apple.com/design/human-interface-guidelines/foundations/typography/#using-custom-fonts:~:text=Using%20system%20fonts-,Using%20custom%20fonts,-Platform%20considerations

2022-07-14 20:22 UTC, ziadali22 commented on UIDokan/Sources/UIDokan/Custom colors fonts/Font+Ext.swift
> +extension UIFont{
this will make it a one extensions , no extension for button or text field or label it will be one extension with generic names ?

2022-07-14 20:27 UTC, ziadali22 commented on UIDokan/Sources/UIDokan/Custom colors fonts/Font+Ext.swift
> +extension UIFont{
should separate them or make one generic names  extension ?

2022-07-15 08:57 UTC, oradwanomar approved these changes

2022-07-15 12:52 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/Extentions/Colors+Ext.swift
> +//  File.swift
`Colors+Styles.swift`

2022-07-15 12:52 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/Extentions/Colors+Ext.swift
> +extension UIColor{
```suggestion
public extension UIColor{
```

2022-07-15 12:52 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/Extentions/Colors+Ext.swift
> +
```suggestion
```

2022-07-15 12:52 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/Extentions/Font+Ext.swift
> +extension UIFont{
```suggestion
extension UIFont {
```

2022-07-15 12:52 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/Extentions/Font+Ext.swift
> +    }
```suggestion
    class public var dokanButton: UIFont {
        return UIFont(name: "DMSans-Medium", size: 14)!
    }
    
    class public var dokanSmallButton: UIFont {
        return UIFont(name: "DMSans-Medium", size: 12)!
    }
```

2022-07-15 12:52 UTC, ahmdmhasn commented
🍩

2022-07-15 17:24 UTC, ziadali22 commented
> One more step closer.

please check it again @ahmdmhasn

2022-07-15 18:27 UTC, merged