verification scene
motoon-eg/dokan-store pull request #55
Opened 2022-07-14 22:53 UTC by ahmednaagy

- make the OTCTextField accessible from outside UIDokan package
- applying few of the comment by @ahmdmhasn

2022-07-15 01:17 UTC, ziadali22 approved these changes

2022-07-15 08:56 UTC, oradwanomar approved these changes

2022-07-15 11:48 UTC, ahmdmhasn requested changes
- PR titles should be more descriptive 
- Not all the comments are addressed 🔫

2022-07-16 13:21 UTC, ahmdmhasn approved these changes

2022-07-17 09:03 UTC, merged

2022-07-17 09:03 UTC, ahmdmhasn commented
I merged it to fix the building issue

2022-07-17 10:36 UTC, ahmdyasser commented
@RaniaZeid you will have conflicts in merging your branch since Nagy has already fixed this issue and merged it.