update swift version at domain and core
motoon-eg/dokan-store pull request #58
Opened 2022-07-16 13:49 UTC by RaniaZeid

2022-07-17 09:05 UTC, ahmdmhasn requested changes
Great effort ya @RaniaZeid. Please note that the pull request should focus on a single change and we should exclude any other unrelated changes.

2022-07-17 09:05 UTC, ahmdmhasn commented on Dokan/Dokan/Scenes/Verification/VerificationViewController.swift
>              // TODO: - Handle the textField upon being filled
To be ignored.

2022-07-17 09:05 UTC, ahmdmhasn commented on Dokan/Dokan/Scenes/Verification/VerificationViewController.xib
>  <?xml version="1.0" encoding="UTF-8"?>
To be ignored.

2022-07-17 09:05 UTC, ahmdmhasn commented on UIDokan/Sources/UIDokan/ReusableViews/OTCTextField.swift
To be ignored.

2022-07-21 13:06 UTC, ahmdyasser commented
@RaniaZeid resolve the conversations to tis PR

2022-07-22 15:30 UTC, ahmdmhasn approved these changes
🚀

2022-07-22 15:32 UTC, ahmednaagy approved these changes

2022-07-22 15:32 UTC, claramounir approved these changes

2022-07-22 15:41 UTC, RaniaZeid reviewed
resolved

2022-07-22 15:43 UTC, merged