add cosmas package
motoon-eg/dokan-store pull request #76
Opened 2022-07-27 21:44 UTC by RaniaZeid

2022-07-29 09:55 UTC, RaniaZeid commented
@ahmdyasser  @ahmednaagy  @oradwanomar  @claramounir  @HebaMad  review please

2022-07-29 11:50 UTC, oradwanomar approved these changes

2022-07-29 14:21 UTC, ahmdmhasn requested changes
It should be added to UIDokan.. and we need to add a wrapper to it.

2022-08-09 09:50 UTC, ahmdmhasn requested changes

2022-08-09 09:50 UTC, ahmdmhasn commented on Cosmas/Package.swift
> +        .package(url: "https://github.com/evgenyneu/Cosmos.git",.upToNextMajor(from: "23.0")
ya Rania it should be added to UIDokan not new one

2022-08-10 20:15 UTC, closed without merging

2022-08-10 20:15 UTC, RaniaZeid commented
another one open #105