Add buttons view to Product Details screen
motoon-eg/dokan-store pull request #79
Opened 2022-07-29 14:25 UTC by ahmednaagy

2022-07-29 20:13 UTC, RaniaZeid commented on Dokan/Dokan/Scenes/ProductDetails/ProductDetailsViewController.swift
> +
make button private
 @IBOutlet weak private var buttonsView: ButtonsView!

2022-07-29 20:14 UTC, RaniaZeid commented on Dokan/Dokan/Scenes/ProductDetails/ProductDetailsViewController.swift
> +
instead of check version you can edit style to default and type to custom from button configuration
at xib file

2022-08-05 22:57 UTC, ahmdmhasn requested changes
Solution is not going to work prior iOS 15 + there's a lot of duplicated code.

2022-08-05 22:57 UTC, ahmdmhasn commented on Dokan/Dokan/Scenes/ProductDetails/Views/BuuttonsView/ButtonsView.swift
> +class ButtonsView: UIView {
```suggestion
class ProductDetailsButtonsView: UIView {
```

2022-08-05 22:57 UTC, ahmdmhasn commented on Dokan/Dokan/Scenes/ProductDetails/Views/BuuttonsView/ButtonsView.swift
> +    private func InitiateButtonsView(){
```suggestion
    private func initiateButtonsView() {
```

2022-08-05 22:57 UTC, ahmdmhasn commented on Dokan/Dokan/Scenes/ProductDetails/ProductDetailsViewController.swift
> +    func setupAddToCartButton() {
Can you test the result on iOS versions before iOS 15?!

2022-08-11 22:51 UTC, ahmdmhasn commented
Do we still need this?

2022-08-19 13:34 UTC, closed without merging